name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-container:
    name: Puild and push new docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push 
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        file: ./Dockerfile
        tags: prottodem/lab4:latest
